### PR TITLE
Added Vorti-Howl

### PR DESCRIPTION
**Pull request by Imacc2009**
I know that there is a CW plugin like this on Coderhire, but this is NOT stolen or converted in anyway. I just want people to have a free version of it.

### CODE REVIEW

**Comment by Imacc2009** [comment]
Dont add this, I just found some bugs which make this useless.

**Comment by Imacc2009** [comment]
Ok, it's fixed now.

**Comment by Chessnut** [comment]
Can you make it so this plugin follows a format similar to the newer plugins? (With the folders and what not)

**Comment by Imacc2009** [comment]
Okay, fixed it.

**Pull request merged**
